name: ci

on:
  push:
    branches: [ "master" ]
    tags: [ "v**" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - uses: gacts/install-hurl@v1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Hurl Tests
      run: ./integration/run.sh

    - run: go build -o xtemplate ./bin
    - run: go build -o caddy ./caddy

    - uses: actions/upload-artifact@v3
      with:
        name: xtemplate
        path: xtemplate

    - uses: actions/upload-artifact@v3
      with:
        name: caddy
        path: caddy
